name: Test
on:
  pull_request:
  push:
permissions:
  contents: read

jobs:
  test:
    # os is not in the matrix, because otherwise there would be way too many testing instances
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16, 18]
        mongo: [4.2, 5.0]
    services:
      mongodb:
        image: mongo:${{ matrix.mongo }}
        ports:
          - 27017:27017
    name: Node ${{ matrix.node }} MongoDB ${{ matrix.mongo }}
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3

      - name: Setup node
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm test
